language: node_js

node_js:
  - "v10.15.3"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - node index.js

script:
  - node_modules/.bin/newman run test/Prog4.postman_collection.json
