language: node_js

node_js:
  - "v10.15.3"

install:
  - npm install mocha chai

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version

script:
  - mocha --exit --reporter list